name: CI test

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: build
      run: |
        # rm -rf node_modules
        npm install
        npm run build
  
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps: 
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        name: id_rsa # optional
    - name: Install packages
      run: sudo apt install openssh-client rsync
    - name: deploy (rsync over ssh)
      run: |
        ssh-keygen -R w11k.de
        rsync . deploy@w11k.de:/srv/www/vhosts/trello-calendar.w11k.de
