name: CI test

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: build
      run: |
        # rm -rf node_modules
        npm install
        npm run build
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
    - name: Install packages
      run: apt install openssh-client rsync
    - name: deploy (rsync over ssh)
      run: rsync . deploy@w11k.de:/srv/www/vhosts/trello-calendar.w11k.de
